stopwords_pt <- tibble(
  palavra = c("que","the","and","was","aweb","o","etc","between","de", "e", "a", "do", "da", "um", "para", "com", 
              "não", "uma", "os", "no", "se", "na", "por", "mais", "as", 
              "dos", "como", "mas", "foi", "ao", "ele", "das", "tem", "à", 
              "seu", "sua", "ou", "ser", "quando", "muito", "nos", "já", 
              "está", "eu", "também", "só", "pelo", "pela", "até", "isso", 
              "ela", "entre", "era", "depois", "sem", "mesmo", "aos", "ter", 
              "seus", "quem", "nas", "me", "esse", "eles", "estão", "você", 
              "tinha", "foram", "essa", "num", "nem", "suas", "meu", "às", 
              "minha", "têm", "numa", "pelos", "elas", "havia", "seja", 
              "qual", "será", "nós", "tenho", "lhe", "deles", "essas", 
              "esses", "pelas", "este", "fosse", "dele", "tu", "te", "vocês",
              "vos", "lhes", "meus", "minhas", "teu", "tua", "teus", "tuas",
              "nosso", "nossa", "nossos", "nossas", "dela", "delas", "esta",
              "estes", "estas", "aquele", "aquela", "aqueles", "aquelas",
              "isto", "aquilo", "pra", "pro", "estou", "estamos", "são","https","link","em","mention",
              "aliancacombolsonaro","whatsapp","channel","compartilhe","é","ex","sobre","bold","após","veja","feira",
              "olhar","soberano","disse","nesta","diz","stickers","animatedsticker","tgs","hashtag",
              "canal","sticker","aplicativo","webp","instantmediabot","vai","pode","si","telegram",
              "dia","agora", "baixe","tudo","paginas","tudo","vídeo","aqui","hoje","by","siga",
              "ainda","webm","anos","live","h","charlie","kirk","há","apenas", "nao", "jaco",
              "jose","chat","intelbrazuca","brazucawars", "blockquote", "tambem", "filhos","vida",
              "pois", "diante", "carater", "antes", "atraves", "forma","voce", "meio", "enquanto","watch",
              "faz", "ze", "qualquer", "geral", "instagram", "sao", "sera", "ja", "cada", "reconhece", 
              "profile", "dizendo", "false", "durante", "alem", "mostra", "v", "los", "assim", "porque",
              "qualquer", "igsh", "deixa", "clara", "juda", "so", "lo","sob", "ano", "ve", "la", "textlink","customemoji", 
              "tiktok", "anuncio", "parcerias", "stickersanimatedsticker", "stickerssticker", "stickersstickerwebp",
              "irao", "que", "não","está", "para","vocês", "com", "tem", "pra", "aqui", "porque",
              "(speaker", "esse", "vou", "vamos", "quem", "uma", "isso", "daqui", "só", "essa", "estou",
              "estão", "estamos", "falando", "ele", "há", "sou", "já", "por", "vem", "lá",
              "aqui", "aí", "daqui", "tá", "speaker", "nao", "ha", "que", "https",
              "animatedsticker", "link", "custom_emoji","para", "whatsapp", "mention",
              "tgs", "uma", "stickers", "como", "text_link", "qrmkucwbmndu5", "animatedsticker.tgs",
              "t.me", "hashtag", "sticker", "wwww.jornaldacidadeonline.com.br","youtube.com", "www.youtube.com",
              "channel", "youtu.be", "mas", "chat.whatsapp.com", "das", "video_files", "watch", "sua",
              "instantmediabot", "webp", "jornaldacidadeonline", "www.instagram.com", "whatsapp.com", "0029va6bzj9kgggajweovm30",
              "qrmkucwkbmndu5", "italic", "bold", "from_caption", "saved", "x.com","www.x.com", "m.youtube.com", "xfwea_xisey",
              "bank","swap","chinese", "ó","gente","ali","coisa", "né", "olha")
)
